AllCops:
  Include:
    - Rakefile
    - Gemfile
    - Guardfile
    - config.ru
  Exclude:
    - tmp/**/*
    - db/**/*
    - vendor/**/*

Rails:
  Enabled: true

Rails/Output:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/BracesAroundHashParameters:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstParameterIndentation:
  Enabled: false
