#!/usr/bin/env ruby
require_relative "src/setup"
require_relative "src/errors"
require_relative "src/scraper"
require_relative "src/serializer"

begin
  Scraper::initialize
  chambers = Scraper.run
  Scraper::Serializer.serialize({ chambers: chambers })
rescue Scraper::Error => error
  puts "[x] scraping failed:"
  puts "[x] #{error.message}"
end
