// flow-typed signature: 064ad7b1080bd1b7cbf1791d5461b450
// flow-typed version: <<STUB>>/http_vx.x.x/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http' {
  declare module.exports: any;
}
