// flow-typed signature: 485f57775485bd39028f2ea9e011047b
// flow-typed version: <<STUB>>/hypernova_v^2.1.3/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hypernova'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hypernova' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hypernova/lib/coordinator' {
  declare module.exports: any;
}

declare module 'hypernova/lib/createGetComponent' {
  declare module.exports: any;
}

declare module 'hypernova/lib/createVM' {
  declare module.exports: any;
}

declare module 'hypernova/lib/environment' {
  declare module.exports: any;
}

declare module 'hypernova/lib/getFiles' {
  declare module.exports: any;
}

declare module 'hypernova/lib/index' {
  declare module.exports: any;
}

declare module 'hypernova/lib/loadModules' {
  declare module.exports: any;
}

declare module 'hypernova/lib/Module' {
  declare module.exports: any;
}

declare module 'hypernova/lib/server' {
  declare module.exports: any;
}

declare module 'hypernova/lib/utils/BatchManager' {
  declare module.exports: any;
}

declare module 'hypernova/lib/utils/lifecycle' {
  declare module.exports: any;
}

declare module 'hypernova/lib/utils/logger' {
  declare module.exports: any;
}

declare module 'hypernova/lib/utils/renderBatch' {
  declare module.exports: any;
}

declare module 'hypernova/lib/worker' {
  declare module.exports: any;
}

declare module 'hypernova/server' {
  declare module.exports: any;
}

declare module 'hypernova/src/coordinator' {
  declare module.exports: any;
}

declare module 'hypernova/src/createGetComponent' {
  declare module.exports: any;
}

declare module 'hypernova/src/createVM' {
  declare module.exports: any;
}

declare module 'hypernova/src/environment' {
  declare module.exports: any;
}

declare module 'hypernova/src/getFiles' {
  declare module.exports: any;
}

declare module 'hypernova/src/index' {
  declare module.exports: any;
}

declare module 'hypernova/src/loadModules' {
  declare module.exports: any;
}

declare module 'hypernova/src/Module' {
  declare module.exports: any;
}

declare module 'hypernova/src/server' {
  declare module.exports: any;
}

declare module 'hypernova/src/utils/BatchManager' {
  declare module.exports: any;
}

declare module 'hypernova/src/utils/lifecycle' {
  declare module.exports: any;
}

declare module 'hypernova/src/utils/logger' {
  declare module.exports: any;
}

declare module 'hypernova/src/utils/renderBatch' {
  declare module.exports: any;
}

declare module 'hypernova/src/worker' {
  declare module.exports: any;
}

declare module 'hypernova/test/a' {
  declare module.exports: any;
}

declare module 'hypernova/test/b' {
  declare module.exports: any;
}

declare module 'hypernova/test/BatchManager-test' {
  declare module.exports: any;
}

declare module 'hypernova/test/checkIso' {
  declare module.exports: any;
}

declare module 'hypernova/test/client-test' {
  declare module.exports: any;
}

declare module 'hypernova/test/components/HypernovaExample' {
  declare module.exports: any;
}

declare module 'hypernova/test/components/nested/component.bundle' {
  declare module.exports: any;
}

declare module 'hypernova/test/coordinator-test' {
  declare module.exports: any;
}

declare module 'hypernova/test/createGetComponent-test' {
  declare module.exports: any;
}

declare module 'hypernova/test/createVM-test' {
  declare module.exports: any;
}

declare module 'hypernova/test/escape-test' {
  declare module.exports: any;
}

declare module 'hypernova/test/getFiles-test' {
  declare module.exports: any;
}

declare module 'hypernova/test/helper' {
  declare module.exports: any;
}

declare module 'hypernova/test/hypernova-runner-test' {
  declare module.exports: any;
}

declare module 'hypernova/test/init' {
  declare module.exports: any;
}

declare module 'hypernova/test/lifecycle-test' {
  declare module.exports: any;
}

declare module 'hypernova/test/loadModules-test' {
  declare module.exports: any;
}

declare module 'hypernova/test/Module-test' {
  declare module.exports: any;
}

declare module 'hypernova/test/mutableArray' {
  declare module.exports: any;
}

declare module 'hypernova/test/renderBatch-test' {
  declare module.exports: any;
}

declare module 'hypernova/test/server-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hypernova/lib/coordinator.js' {
  declare module.exports: $Exports<'hypernova/lib/coordinator'>;
}
declare module 'hypernova/lib/createGetComponent.js' {
  declare module.exports: $Exports<'hypernova/lib/createGetComponent'>;
}
declare module 'hypernova/lib/createVM.js' {
  declare module.exports: $Exports<'hypernova/lib/createVM'>;
}
declare module 'hypernova/lib/environment.js' {
  declare module.exports: $Exports<'hypernova/lib/environment'>;
}
declare module 'hypernova/lib/getFiles.js' {
  declare module.exports: $Exports<'hypernova/lib/getFiles'>;
}
declare module 'hypernova/lib/index.js' {
  declare module.exports: $Exports<'hypernova/lib/index'>;
}
declare module 'hypernova/lib/loadModules.js' {
  declare module.exports: $Exports<'hypernova/lib/loadModules'>;
}
declare module 'hypernova/lib/Module.js' {
  declare module.exports: $Exports<'hypernova/lib/Module'>;
}
declare module 'hypernova/lib/server.js' {
  declare module.exports: $Exports<'hypernova/lib/server'>;
}
declare module 'hypernova/lib/utils/BatchManager.js' {
  declare module.exports: $Exports<'hypernova/lib/utils/BatchManager'>;
}
declare module 'hypernova/lib/utils/lifecycle.js' {
  declare module.exports: $Exports<'hypernova/lib/utils/lifecycle'>;
}
declare module 'hypernova/lib/utils/logger.js' {
  declare module.exports: $Exports<'hypernova/lib/utils/logger'>;
}
declare module 'hypernova/lib/utils/renderBatch.js' {
  declare module.exports: $Exports<'hypernova/lib/utils/renderBatch'>;
}
declare module 'hypernova/lib/worker.js' {
  declare module.exports: $Exports<'hypernova/lib/worker'>;
}
declare module 'hypernova/server.js' {
  declare module.exports: $Exports<'hypernova/server'>;
}
declare module 'hypernova/src/coordinator.js' {
  declare module.exports: $Exports<'hypernova/src/coordinator'>;
}
declare module 'hypernova/src/createGetComponent.js' {
  declare module.exports: $Exports<'hypernova/src/createGetComponent'>;
}
declare module 'hypernova/src/createVM.js' {
  declare module.exports: $Exports<'hypernova/src/createVM'>;
}
declare module 'hypernova/src/environment.js' {
  declare module.exports: $Exports<'hypernova/src/environment'>;
}
declare module 'hypernova/src/getFiles.js' {
  declare module.exports: $Exports<'hypernova/src/getFiles'>;
}
declare module 'hypernova/src/index.js' {
  declare module.exports: $Exports<'hypernova/src/index'>;
}
declare module 'hypernova/src/loadModules.js' {
  declare module.exports: $Exports<'hypernova/src/loadModules'>;
}
declare module 'hypernova/src/Module.js' {
  declare module.exports: $Exports<'hypernova/src/Module'>;
}
declare module 'hypernova/src/server.js' {
  declare module.exports: $Exports<'hypernova/src/server'>;
}
declare module 'hypernova/src/utils/BatchManager.js' {
  declare module.exports: $Exports<'hypernova/src/utils/BatchManager'>;
}
declare module 'hypernova/src/utils/lifecycle.js' {
  declare module.exports: $Exports<'hypernova/src/utils/lifecycle'>;
}
declare module 'hypernova/src/utils/logger.js' {
  declare module.exports: $Exports<'hypernova/src/utils/logger'>;
}
declare module 'hypernova/src/utils/renderBatch.js' {
  declare module.exports: $Exports<'hypernova/src/utils/renderBatch'>;
}
declare module 'hypernova/src/worker.js' {
  declare module.exports: $Exports<'hypernova/src/worker'>;
}
declare module 'hypernova/test/a.js' {
  declare module.exports: $Exports<'hypernova/test/a'>;
}
declare module 'hypernova/test/b.js' {
  declare module.exports: $Exports<'hypernova/test/b'>;
}
declare module 'hypernova/test/BatchManager-test.js' {
  declare module.exports: $Exports<'hypernova/test/BatchManager-test'>;
}
declare module 'hypernova/test/checkIso.js' {
  declare module.exports: $Exports<'hypernova/test/checkIso'>;
}
declare module 'hypernova/test/client-test.js' {
  declare module.exports: $Exports<'hypernova/test/client-test'>;
}
declare module 'hypernova/test/components/HypernovaExample.js' {
  declare module.exports: $Exports<'hypernova/test/components/HypernovaExample'>;
}
declare module 'hypernova/test/components/nested/component.bundle.js' {
  declare module.exports: $Exports<'hypernova/test/components/nested/component.bundle'>;
}
declare module 'hypernova/test/coordinator-test.js' {
  declare module.exports: $Exports<'hypernova/test/coordinator-test'>;
}
declare module 'hypernova/test/createGetComponent-test.js' {
  declare module.exports: $Exports<'hypernova/test/createGetComponent-test'>;
}
declare module 'hypernova/test/createVM-test.js' {
  declare module.exports: $Exports<'hypernova/test/createVM-test'>;
}
declare module 'hypernova/test/escape-test.js' {
  declare module.exports: $Exports<'hypernova/test/escape-test'>;
}
declare module 'hypernova/test/getFiles-test.js' {
  declare module.exports: $Exports<'hypernova/test/getFiles-test'>;
}
declare module 'hypernova/test/helper.js' {
  declare module.exports: $Exports<'hypernova/test/helper'>;
}
declare module 'hypernova/test/hypernova-runner-test.js' {
  declare module.exports: $Exports<'hypernova/test/hypernova-runner-test'>;
}
declare module 'hypernova/test/init.js' {
  declare module.exports: $Exports<'hypernova/test/init'>;
}
declare module 'hypernova/test/lifecycle-test.js' {
  declare module.exports: $Exports<'hypernova/test/lifecycle-test'>;
}
declare module 'hypernova/test/loadModules-test.js' {
  declare module.exports: $Exports<'hypernova/test/loadModules-test'>;
}
declare module 'hypernova/test/Module-test.js' {
  declare module.exports: $Exports<'hypernova/test/Module-test'>;
}
declare module 'hypernova/test/mutableArray.js' {
  declare module.exports: $Exports<'hypernova/test/mutableArray'>;
}
declare module 'hypernova/test/renderBatch-test.js' {
  declare module.exports: $Exports<'hypernova/test/renderBatch-test'>;
}
declare module 'hypernova/test/server-test.js' {
  declare module.exports: $Exports<'hypernova/test/server-test'>;
}
