// flow-typed signature: 79069963cadee8a9930540aea9f2bb19
// flow-typed version: <<STUB>>/hypernova-react_vhttps://github.com/legislated/hypernova-react.git/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hypernova-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hypernova-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hypernova-react/lib/index' {
  declare module.exports: any;
}

declare module 'hypernova-react/src/index' {
  declare module.exports: any;
}

declare module 'hypernova-react/test/components/ExampleReactComponent' {
  declare module.exports: any;
}

declare module 'hypernova-react/test/components/HypernovaExampleReact' {
  declare module.exports: any;
}

declare module 'hypernova-react/test/init' {
  declare module.exports: any;
}

declare module 'hypernova-react/test/renderReact-test' {
  declare module.exports: any;
}

declare module 'hypernova-react/test/renderReactStatic-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hypernova-react/lib/index.js' {
  declare module.exports: $Exports<'hypernova-react/lib/index'>;
}
declare module 'hypernova-react/src/index.js' {
  declare module.exports: $Exports<'hypernova-react/src/index'>;
}
declare module 'hypernova-react/test/components/ExampleReactComponent.js' {
  declare module.exports: $Exports<'hypernova-react/test/components/ExampleReactComponent'>;
}
declare module 'hypernova-react/test/components/HypernovaExampleReact.js' {
  declare module.exports: $Exports<'hypernova-react/test/components/HypernovaExampleReact'>;
}
declare module 'hypernova-react/test/init.js' {
  declare module.exports: $Exports<'hypernova-react/test/init'>;
}
declare module 'hypernova-react/test/renderReact-test.js' {
  declare module.exports: $Exports<'hypernova-react/test/renderReact-test'>;
}
declare module 'hypernova-react/test/renderReactStatic-test.js' {
  declare module.exports: $Exports<'hypernova-react/test/renderReactStatic-test'>;
}
