// flow-typed signature: 3b1292dc818d4bc364123245276e677f
// flow-typed version: <<STUB>>/react-router-scroll-4_v^1.0.0-beta.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-scroll-4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-scroll-4' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-scroll-4/lib/react-router-scroll-4.es' {
  declare module.exports: any;
}

declare module 'react-router-scroll-4/lib/react-router-scroll-4' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-scroll-4/lib/react-router-scroll-4.es.js' {
  declare module.exports: $Exports<'react-router-scroll-4/lib/react-router-scroll-4.es'>;
}
declare module 'react-router-scroll-4/lib/react-router-scroll-4.js' {
  declare module.exports: $Exports<'react-router-scroll-4/lib/react-router-scroll-4'>;
}
